package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Thursday, November 3, 2016 10:02:40 PM GMT
*/

public interface HelloOperations 
{
  String hellomessage ();
  void hellomessage (String newHellomessage);
} // interface HelloOperations
